version: '3.9'

services:
  database:
    container_name: cirurgic-request-database
    image: mysql:8.0.30-debian
    environment:
      MYSQL_DATABASE: cirurgic_request
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - 3306:3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  backend:
    container_name: cirurgic-request-backend
    build:
      context: ./cirurgic-request-backend
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: 'mysql://root:root@database:3306/cirurgic_request'
    depends_on:
      database:
        condition: service_healthy

  frontend:
    container_name: cirurgic-request-frontend
    build:
      context: ./cirurgic-request-frontend
    ports:
      - 3000:5173
